### ISSUE TITLE
fuzzel

### ISSUE THREAD

**Issue by pizzav-xyz** [jazz1n/dotfiles#1]
how do i manually download the config for fuzzel and how do i bind it?

**Comment by jazz1n** [comment]
Hey, the config for fuzzel is in: .config/fuzzel directory. you can download the code as zip and extract it and put whichever one (fuzzel-cyberpunk.ini or fuzzel-gruvbox.ini) in this directory: ~/.config/fuzzel. Just remember to rename it to fuzzel.ini

and as to how to bind it:
In .config/hypr/hyprland.conf I have these lines for binding fuzzel to Mod + R shortcut.

$menu = fuzzel
bind = $mainMod, R, exec, $menu

you can probably just have it in one line like this:
bind = $mainMod, R, exec, fuzzel

let me know if this helps :)

**Comment by pizzav-xyz** [comment]
thanks
